# Generated by Django 5.2.11 on 2026-02-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed')], max_length=10, verbose_name='Transaction Type')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, max_length=15, null=True, verbose_name='Reference Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.reward')),
            ],
            options={
                'verbose_name': 'Reward Transaction',
                'verbose_name_plural': 'Reward Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
