# Generated by Django 5.2.11 on 2026-02-11 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='total_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Points'),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, max_length=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reference Amount'),
        ),
        migrations.AlterField(
            model_name='rewardtransaction',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points'),
        ),
    ]
